-- ============================================================================
-- DEPRECATED FILE — DO NOT RUN DIRECTLY
-- ============================================================================
--
-- The previous version of this file contained `DROP TABLE IF EXISTS` statements
-- that would destroy production data if accidentally executed. Per Codex Round 2
-- review (2026-04-28), schema is now split:
--
-- 1. **Production / re-validation** — idempotent, safe to re-run:
--      wrangler d1 execute nexgen-prod --file migrations/0001_baseline.sql
--
-- 2. **Future schema changes** — numbered migrations in `migrations/`:
--      migrations/0002_<name>.sql, 0003_<name>.sql, ...
--      Each migration must be idempotent (use IF NOT EXISTS / IF EXISTS).
--
-- 3. **Fresh test DB initialization** — DESTRUCTIVE, never run on prod:
--      wrangler d1 execute <test-db> --file schema-fresh-init.sql
--      followed by: migrations/0001_baseline.sql
--
-- ============================================================================

-- Intentionally empty. Use the files above.
